apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 2 # Kubernetes will keep 2 copies of your app running!
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: kunju33/proj1:latest # Your image from Docker Hub
          ports:
            - containerPort: 3000
          resources: # <--- Add this section
            requests:
              memory: "64Mi" # Minimum RAM needed
              cpu: "100m" # Minimum CPU (10% of 1 core)
            limits:
              memory: "128Mi" # Maximum RAM allowed
              cpu: "500m" # Maximum CPU (50% of 1 core)
