apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-app # This MUST match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80 # The port you will type in your browser
      targetPort: 3000 # The port your Node.js code is listening on
